Repository akiomik/nostrends, pull requests merged in 2023-02, with the labels that each got.

#1 fix: profile links
  src/lib/Profile.ts
Labels: bug

#4 Fix Profile#isNip05Valid when empty
  src/entities/Profile.ts
  tests/entities/Profile.test.ts
Labels: bug

#5 Improve note loading
  src/components/LoadingSpinner.svelte
  src/components/NoteList.svelte
  src/components/RegionTabPanel.svelte
  src/lib/NoteLoader.ts
  src/routes/+page.svelte
  src/routes/+page.ts
Labels: enhancement

#6 Fix minor issues
  src/components/ProfileNip05.svelte
  src/lib/AsyncRelay.ts
  src/lib/NoteLoader.ts
Labels: bug

#7 Use absolute import instead of relative import
  .gitignore
  README.md
  package.json
  src/lib/components/Footer.svelte
  src/lib/components/Header.svelte
  src/lib/components/LoadingSpinner.svelte
  src/lib/components/Modal.svelte
  src/lib/components/NoteLink.svelte
  src/lib/components/NoteList.svelte
  src/lib/components/NoteListItem.svelte
  src/lib/components/NoteListItemProfile.svelte
  src/lib/components/ProfileLink.svelte
  src/lib/components/ProfileNip05.svelte
  src/lib/components/SettingModal.svelte
  src/lib/entities/Note.ts
  src/lib/entities/Profile.ts
  src/lib/entities/Region.ts
  src/lib/entities/Regions.ts
  src/lib/entities/SortOrdering.ts
  src/lib/entities/Tag.ts
  src/lib/events/.gitkeep
  src/lib/packages/nostr-tools.ts
  src/lib/services/AsyncRelay.ts
  src/lib/services/NoteContentFormatter.ts
  src/lib/services/NoteLoader.ts
  src/lib/services/NoteSorter.ts
  src/lib/services/ReactionCountJsonLoader.ts
  src/lib/stores/settings.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/+page.ts
  tests/entities/Note.test.ts
  tests/entities/Profile.test.ts
  tests/entities/Region.test.ts
Labels: refactoring

#8 Fix event path
  .github/workflows/deploy.yml
Labels: bug

#9 Make loading async
  src/lib/components/NoteList.svelte
  src/lib/components/NoteListItem.svelte
  src/lib/entities/Note.ts
  src/lib/entities/Profile.ts
  src/lib/services/AsyncRelay.ts
  src/lib/services/NoteLoader.ts
  src/routes/+page.svelte
  src/routes/+page.ts
  tests/entities/Note.test.ts
  tests/entities/Profile.test.ts
  tsconfig.json
Labels: enhancement

#18 Fix misc
  src/lib/components/ExternalLink.svelte
  src/lib/components/Footer.svelte
  src/lib/components/Header.svelte
  src/lib/components/NoteLink.svelte
  src/lib/components/NoteList.svelte
  src/lib/components/NoteListItem.svelte
  src/lib/components/NoteListItemProfile.svelte
  src/lib/components/ProfileLink.svelte
  src/lib/components/ProfileNip05.svelte
  src/lib/components/SettingsModal.svelte
  src/lib/services/NoteContentFormatter.ts
  src/routes/+page.svelte
Labels: enhancement

#23 Fix tab overflow
  src/routes/+page.svelte
Labels: bug

#26 Reuse connection
  src/lib/entities/DataSource.ts
  src/lib/entities/DataSources.ts
  src/lib/entities/Region.ts
  src/lib/services/NostrClient.ts
  src/lib/services/NoteLoader.ts
  src/lib/services/SummaryNoteLoader.ts
  src/routes/+page.svelte
  src/routes/+page.ts
  tests/entities/DataSource.test.ts
Labels: enhancement
